version: '3.8'

services:
  back-end:
    build: ./back-end
    ports:
      - "5252:5252"
    expose:
      - "5252"


  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task5
    # PORTS XƏTTİ SİLİN
    # ports:
    #   - "5252:5252"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
